### PR TITLE
[WIP] Add charts

### PR DESCRIPTION
**Pull request by NunoSempere**
This branch adds charts. It is a work in progress, and thus not ready to be merged.
chart2

To do:
- [ ] Use real rather than fake data. I'm hoping the graphql interface can be used for this, rather than having to interact with it directly
- [ ] Reduce the chart size. Take https://manifold.markets/ or https://polymarket.com/ as reference points
  - As a sidenote, I think I'm accustomed to much bigger fonts than normal, so my personal preference shouldn't really be a guiding factor here.
- [ ] Add functionality so that charts can be embedded
- [ ] Only display the yes in the case of a binary question
- [ ] Add the ability to combine many questions at once, maybe with shorthand labels in the url query
- [ ] Add bells and whistles: Different options, allow one to consider different time periods, show quality indicators, add zoom ability, add other functionality in https://polymarket.com (they recently did a really nice chart refactoring)
- [ ] Incorporate some feedback from [twitter](https://twitter.com/NunoSempere/status/1516763181489737729), and generally from @ClayGraubard or @uvafan 
- [ ] Embed into EA Forum/LessWrong

Overall my sense is that these are already better than Metaculus/CultivateLabs charts. I think we should be aiming to be at least as nice as Manifold Markets or https://globalguessing.com/russia-ukraine-forecasts/, e.g., nice enough that the Global Guessing team replaces their current charts with ours.

My sense is that @berekuk might particularly enjoy integrating this with EA Forum/LessWrong. Ideally, you @berekuk might also be up for helping out with this or directly take over after finishing with the grapqhl api, but I'm also up for working on this more slowly.

### CODE REVIEW

**Comment by uvafan** [comment]
We're using Nivo for the charts on Stradam, similar to Manifold Markets who we saw the code from I think from a response to you on their Discord; why did you decide to use Victory instead? 

Your chart looks pretty good to me already; one minor suggestion is to label like 21 Apr 2022 rather than 21/04/2022 as the default way dates are written in the US is MM/DD/YYYY which might make your current display confusing to US users

**Comment by NunoSempere** [comment]
> why did you decide to use Victory instead?

I had a look at nivo, tried playing with it, and came to the conclusion that their incentives were too skewed in the direction of using their svg api. I also personally like the aesthetic of formidable.com more (and I think we are using urql, also from them, in our codebase)

**Comment by Platinuman** [comment]
Another small comment about charts, likely you'll want the tooltip to display multiple options if the points are close (esp for categorical questions)

**Comment by akrolsmir** [comment]
Just a flyby to say - this is super cool, I'm looking forward to charts on Metaforecast! And even more so if we could develop some kind of charting library that both Metaforecast and Manifold use. Obviously, would be happy to provide my personal UX feedback, or chat more about integrating together~

Metaculus might be interested too -- Daniel (their director of engineering) has spoken about wanting to open-source their charting components as well.

**Comment by berekuk** [comment]
Continuing on #74 since it was easier to copy-paste just some parts of the code there than to merge this with current master.

**Pull request closed without merging**
