### PR TITLE
Embed question page

### PR DESCRIPTION
**Pull request by berekuk**
For #77.

### CODE REVIEW

**Comment by berekuk** [comment]
(from #77)

> Things to consider:
> - Size

Responsive, with recommended 600x600 pixels in html code, which should be enough to fit the chart and options, probably with a scrollbar, but options should fit in a visible area.

> - Caching?

None; I'm not sure if our database will handle the load if someone embeds the chart on >10 rps page, but I think it's ok not to optimize this for now.

> - Customizability?

None. Let's wait for user requests instead of trying to guess.

---

Discoverability: I added an `Embed` section on each question's page.

Overall, question page layout is becoming messy, I'm going to experiment a bit with different headings and alignments before merging.

**Comment by NunoSempere** [comment]
This is beautiful

**Comment by NunoSempere** [comment]
@ClayGr, check it out

**Comment by NunoSempere** [comment]
(See also: https://github.com/ForumMagnum/ForumMagnum/pull/4907 and https://github.com/ForumMagnum/ForumMagnum/pull/4728 for how to integrate this with LW)

**Comment by berekuk** [comment]
> https://github.com/ForumMagnum/ForumMagnum/pull/4907 and https://github.com/ForumMagnum/ForumMagnum/pull/4907

These links are identical, should one of them be different?

**Comment by NunoSempere** [comment]
Yeah, changed

**Comment by berekuk** [comment]
Some updates:
- moved "capture" and "embed" inside the question card
- restyled headings
- capture image is now resizable with [re-resizable](https://github.com/bokuweb/re-resizable)
- preview link for embed

(I plan to implement LW embeds and #89 in separate PRs, this one is for embed feature only)

**Comment by berekuk** [comment]
Also: section anchor links, because why not.

**Comment by berekuk** [comment]
Oops, my push failed due to rebase and I haven't noticed. Will open a separate PR.

**Pull request merged**
